version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Detect OS and install packages
      - if [ -f /etc/debian_version ]; then apt-get update -y && apt-get install -y jq awscli docker.io; fi
      - if [ -f /etc/redhat-release ]; then yum install -y jq awscli docker; fi
      - if [ -f /etc/al2023-release ]; then dnf install -y jq awscli docker; fi

  pre_build:
    commands:
      - echo "Setting environment variables..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=us-east-1
      - REPOSITORY=devops-app
      - IMAGE_TAG=$(date +%Y%m%d%H%M)
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY .
      - echo "Tagging image..."
      - docker tag $REPOSITORY:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$IMAGE_TAG
      - echo "Saving image tag..."
      - echo $IMAGE_TAG > imageTag.txt

artifacts:
  files:
    - imageTag.txt
    - eks/deployment.yaml
    - eks/service.yaml
