version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo "Loading variables..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=us-east-1
      - CLUSTER_NAME=confused-folk-dinosaur
      - REPOSITORY=devops-app
      - IMAGE_TAG=$(cat imageTag.txt)

      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

  build:
    commands:
      - echo "Updating deployment manifest with new image..."
      - sed -i "s|IMAGE_PLACEHOLDER|$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$IMAGE_TAG|g" eks/deployment.yaml

  post_build:
    commands:
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f eks/deployment.yaml
      - kubectl apply -f eks/service.yaml
      - echo "Deployment completed successfully!"
